#ifndef DEFINES_H
#define DEFINES_H "DEFINES_H"

#define BOOKED 1
#define UNBOOKED 0
#define LOGGED_IN 1
#define LOGGED_OUT 0
#define DUPLICATE_INFORMATION 0
#define REGISTER_SUCCSESS 1
#define SKIP_FIRST_LINE 999999
#define AFTER_QUESTION_MARK 3
#define CORRECT_SIGN_INFORMATION 3
#define CORRECT_WALLET_INFORMATION 1
#define MAX_STAR 5
#define MIN_STAR 1
#define MIN_PRICE 0
#define SPECIFIC_ROOM_FILTER_ENOUGH_INFORMATION 11
#define SPECIFIC_ROOM_FILTER_CORRECT_INFORMATION 4
#define MIN_QUANTITY 1
#define NO_DUPLICATE_FILTER_FOUND -1
#define CORRECT_LOGIN_INFORMATION 1
#define INCORRECT_LOGIN_INFORMATION 0
#define RESERVES_CORRECT_INFORMATION 5
#endif